import json
import hashlib
from collections import defaultdict

def generate_hash(s):
    return hashlib.sha256(s.encode('utf-8')).hexdigest()

def analyze():
    with open('code_base.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Rebuild class definitions
    # Map class name -> List of files it was defined in
    class_definitions = defaultdict(list)
    for item in data:
        path = item.get('path', '')
        for cls in item.get('classes', []):
            name = cls.get('name')
            if name:
                class_definitions[name].append(path)

    # 1. ExternalClass explosion and Method Resolution
    method_resolution_report = "# Method Resolution Report\n\n"
    method_resolution_report += "| Method ID | Method Name | Expected Parent Class | Reason |\n"
    method_resolution_report += "|---|---|---|---|\n"
    
    failure_analysis = "# Phase 2B Failure Analysis\n\n"
    
    methods_loaded = 0
    methods_attached_to_class = 0
    methods_attached_to_external = 0
    
    unique_method_ids = set()
    method_duplicates = 0
    
    external_classes_created = set()
    unresolved_class_names = set()

    for item in data:
        path = item.get('path', '')
        for md in item.get('methods', []):
            m_name = md.get('name')
            c_name = md.get('class')
            if not m_name or not c_name: continue
            
            params = md.get('parameters', [])
            param_str = ", ".join(p.get('type', '') for p in params)
            signature = f"{m_name}({param_str})"
            
            raw_id = f"{path}::{c_name}::{m_name}::{signature}"
            method_id = generate_hash(raw_id)
            
            if method_id in unique_method_ids:
                method_duplicates += 1
                continue
            unique_method_ids.add(method_id)
            methods_loaded += 1
            
            if c_name in class_definitions:
                methods_attached_to_class += 1
            else:
                methods_attached_to_external += 1
                external_classes_created.add(c_name)
                unresolved_class_names.add(c_name)
                
                # Check why it's missing. Was it parsed with a namespace?
                # For example, "SPAposition" might be parsed as "SPAposition" in classes but the method says "class": "position"?
                # Let's find partial matches
                partial_matches = [k for k in class_definitions.keys() if c_name in k or k in c_name]
                reason = "Class not found in parsed definitions."
                if partial_matches:
                    reason += f" Partial matches: {partial_matches}"
                
                method_resolution_report += f"| {method_id[:8]}... | {m_name} | {c_name} | {reason} |\n"

    # Function Analysis
    functions_loaded = 0
    unique_function_ids = set()
    func_duplicates = 0
    malformed_signatures = 0
    
    func_dups_detail = defaultdict(list)
    
    for item in data:
        path = item.get('path', '')
        for fn in item.get('functions', []):
            f_name = fn.get('name')
            if not f_name: continue
            
            params = fn.get('parameters', [])
            param_str = ", ".join(p.get('type', '') for p in params)
            signature = f"{f_name}({param_str})"
            
            if not param_str and "void" not in param_str and not params:
                # Could be a malformed signature if there are no params but it's not void? Actually C++ allows empty params `()`
                pass
            
            raw_id = f"{path}::{f_name}::{signature}"
            func_id = generate_hash(raw_id)
            
            if func_id in unique_function_ids:
                func_duplicates += 1
                func_dups_detail[raw_id].append(fn)
                continue
            
            unique_function_ids.add(func_id)
            functions_loaded += 1

    failure_analysis += f"## 1. ExternalClass Explosion\n"
    failure_analysis += f"- External Classes generated by Method resolution: {len(external_classes_created)}\n"
    failure_analysis += f"- Unresolved Class Names: {list(unresolved_class_names)[:20]}... (Total: {len(unresolved_class_names)})\n\n"
    
    failure_analysis += f"## 2. Function Ingestion Audit\n"
    failure_analysis += f"- Functions in JSON: 30833\n"
    failure_analysis += f"- Unique Function IDs loaded: {functions_loaded}\n"
    failure_analysis += f"- Duplicates strictly due to identical `file_path::function_name::signature`: {func_duplicates}\n\n"
    
    failure_analysis += f"## 3. Method Ingestion Audit\n"
    failure_analysis += f"- Methods in JSON: 6554\n"
    failure_analysis += f"- Unique Method IDs loaded: {methods_loaded}\n"
    failure_analysis += f"- Duplicates strictly due to identical `file_path::class_name::method_name::signature`: {method_duplicates}\n"
    failure_analysis += f"- Methods correctly mapped to Class: {methods_attached_to_class}\n"
    failure_analysis += f"- Methods incorrectly mapped to ExternalClass: {methods_attached_to_external}\n\n"

    with open('phase2b_failure_analysis.md', 'w', encoding='utf-8') as f:
        f.write(failure_analysis)
        
    with open('method_resolution_report.md', 'w', encoding='utf-8') as f:
        f.write(method_resolution_report)
        
    print(f"Functions Loaded: {functions_loaded}")
    print(f"Function Duplicates: {func_duplicates}")
    print(f"Methods Loaded: {methods_loaded}")
    print(f"Method Duplicates: {method_duplicates}")
    print(f"Methods attached to class: {methods_attached_to_class}")
    print(f"Methods attached to external: {methods_attached_to_external}")
    print(f"Top func dups: {list(func_dups_detail.keys())[:5]}")

if __name__ == '__main__':
    analyze()
