import re

with open('multi_repo.py', 'r', encoding='utf-8') as f:
    code = f.read()

start_marker = "    temp_functions = []\n"
end_marker = "    # Helpers for function AST analysis\n"

idx_start = code.find(start_marker)
idx_end = code.find(end_marker)

if idx_start != -1 and idx_end != -1:
    new_logic = """
    def text(node):
        return code[node.start_byte:node.end_byte].decode("utf-8", errors="ignore")

    comments = []
    def walk_comments(n):
        if n.type == 'comment':
            comments.append({
                "text": text(n),
                "end_line": n.end_point[0] + 1
            })
        for c in n.children:
            walk_comments(c)
    walk_comments(tree.root_node)

    def clean_comment(comment_text):
        lower_c = comment_text.lower()
        if "copyright" in lower_c or "license" in lower_c:
            return None
        if "generated by" in lower_c or "generated file" in lower_c:
            return None
        if "revision" in lower_c or "history" in lower_c:
            return None
        
        stripped = comment_text.replace('/', '').replace('*', '').strip()
        if not stripped:
            return None
        if len(stripped) > 5 and len(set(stripped)) == 1 and stripped[0] in '=-_':
            return None
            
        lines = comment_text.split('\\n')
        cleaned_lines = []
        for line in lines:
            line = line.strip()
            if line.startswith('///'): line = line[3:]
            elif line.startswith('//'): line = line[2:]
            elif line.startswith('/**'): line = line[3:]
            elif line.startswith('/*'): line = line[2:]
            
            if line.endswith('*/'): line = line[:-2]
            if line.startswith('*'): line = line[1:]
            
            line = line.strip()
            if line:
                cleaned_lines.append(line)
                
        if not cleaned_lines:
            return None
            
        import re
        raw_text = "\\n".join(cleaned_lines)
        raw_text = re.sub(r'\\[([^\\]]+)\\]\\([^\\)]+\\)', r'\\1', raw_text)
        raw_text = re.sub(r'<[^>]+>', '\\n', raw_text)
        raw_text = raw_text.replace('&nbsp;', ' ').replace('&lt;', '<').replace('&gt;', '>').replace('&amp;', '&')
        
        raw_lines = raw_text.split('\\n')
        normalized_lines = []
        for line in raw_lines:
            line = re.sub(r'[ \\t]+', ' ', line).strip()
            if line:
                normalized_lines.append(line)
                
        final_lines = []
        for line in normalized_lines:
            if re.match(r'^(@[a-zA-Z]+|Role:|Effect:|Journal:|Product\\(s\\):|Limitations:|Technical Articles:|Note:)', line, re.IGNORECASE):
                final_lines.append("\\n" + line)
            else:
                final_lines.append(" " + line)
                
        text_out = "".join(final_lines).strip()
        text_out = re.sub(r'[ \\t]+', ' ', text_out)
        text_out = re.sub(r'\\n\\s+', '\\n', text_out).strip()
        
        return text_out

    valid_comments = []
    for c in comments:
        cleaned = clean_comment(c["text"])
        if cleaned:
            valid_comments.append({
                "text": cleaned,
                "end_line": c["end_line"]
            })
            
    valid_comments.sort(key=lambda x: x["end_line"])

    def get_closest_comment(entity_line):
        closest = None
        min_dist = float('inf')
        for c in valid_comments:
            dist = entity_line - c["end_line"]
            if 0 <= dist <= 3:
                if dist < min_dist:
                    min_dist = dist
                    closest = c["text"]
        return closest

"""
    code = code[:idx_start + len(start_marker)] + new_logic + code[idx_end:]

    with open('multi_repo.py', 'w', encoding='utf-8') as f:
        f.write(code)
    print("Fixed multi_repo.py")
else:
    print("Markers not found!")
