import re

with open('multi_repo.py', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Inject valid_comments logic right after temp_functions = []
comment_logic = """
    comments = []
    def walk_comments(n):
        if n.type == 'comment':
            comments.append({
                "text": text(n),
                "end_line": n.end_point[0] + 1
            })
        for c in n.children:
            walk_comments(c)
    walk_comments(tree.root_node)

    def clean_comment(comment_text):
        lower_c = comment_text.lower()
        if "copyright" in lower_c or "license" in lower_c:
            return None
        if "generated by" in lower_c or "generated file" in lower_c:
            return None
        if "revision" in lower_c or "history" in lower_c:
            return None
        
        stripped = comment_text.replace('/', '').replace('*', '').strip()
        if not stripped:
            return None
        if len(stripped) > 5 and len(set(stripped)) == 1 and stripped[0] in '=-_':
            return None
            
        lines = comment_text.split('\\n')
        cleaned_lines = []
        for line in lines:
            line = line.strip()
            if line.startswith('///'): line = line[3:]
            elif line.startswith('//'): line = line[2:]
            elif line.startswith('/**'): line = line[3:]
            elif line.startswith('/*'): line = line[2:]
            
            if line.endswith('*/'): line = line[:-2]
            if line.startswith('*'): line = line[1:]
            
            line = line.strip()
            if line:
                cleaned_lines.append(line)
                
        if not cleaned_lines:
            return None
            
        return "\\n".join(cleaned_lines)

    valid_comments = []
    for c in comments:
        cleaned = clean_comment(c["text"])
        if cleaned:
            valid_comments.append({
                "text": cleaned,
                "end_line": c["end_line"]
            })
            
    valid_comments.sort(key=lambda x: x["end_line"])

    def get_closest_comment(entity_line):
        closest = None
        min_dist = float('inf')
        for c in valid_comments:
            dist = entity_line - c["end_line"]
            if 0 <= dist <= 3:
                if dist < min_dist:
                    min_dist = dist
                    closest = c["text"]
        return closest
"""
content = content.replace("    temp_functions = []\n", "    temp_functions = []\n" + comment_logic)

# 2. Change classes, structs, enums initializers
content = content.replace("    classes = set()", "    classes = {}")
content = content.replace("    structs = set()", "    structs = {}")
content = content.replace("    enums = set()", "    enums = {}")

# 3. Change classes.add(...)
content = content.replace(
    "classes.add(class_name)",
    """doc = get_closest_comment(node.start_point[0] + 1)
                        if class_name not in classes or not classes[class_name].get("documentation"):
                            classes[class_name] = {"name": class_name, "documentation": doc}"""
)

# 4. Change structs.add(...)
content = re.sub(
    r"structs\.add\((.*?)\)",
    r"""s_name = \1
                doc = get_closest_comment(node.start_point[0] + 1)
                if s_name not in structs or not structs[s_name].get("documentation"):
                    structs[s_name] = {"name": s_name, "documentation": doc}""",
    content
)

# 5. Change enums.add(...)
content = re.sub(
    r"enums\.add\((.*?)\)",
    r"""e_name = \1
                    doc = get_closest_comment(node.start_point[0] + 1)
                    if e_name not in enums or not enums[e_name].get("documentation"):
                        enums[e_name] = {"name": e_name, "documentation": doc}""",
    content
)

# 6. Change function tracking to add documentation
content = content.replace(
    '"line_number": node.start_point[0] + 1\n                            })',
    '"line_number": node.start_point[0] + 1,\n                                "documentation": get_closest_comment(node.start_point[0] + 1)\n                            })'
)

# 7. Change local_types = classes.union...
content = content.replace(
    "local_types = classes.union(structs).union(enums).union(typedefs)",
    "local_types = set(classes.keys()).union(structs.keys()).union(enums.keys()).union(typedefs)"
)

# 8. Change return values in parse_file
content = content.replace(
    '"classes": sorted(classes)',
    '"classes": sorted(list(classes.values()), key=lambda x: x["name"])'
)
content = content.replace(
    '"structs": sorted(structs)',
    '"structs": sorted(list(structs.values()), key=lambda x: x["name"])'
)
content = content.replace(
    '"enums": sorted(enums)',
    '"enums": sorted(list(enums.values()), key=lambda x: x["name"])'
)

# 9. Change phase 1 global update
content = content.replace(
    'global_classes.update(item.get("classes", []))',
    'global_classes.update(c["name"] for c in item.get("classes", []))'
)
content = content.replace(
    'global_structs.update(item.get("structs", []))',
    'global_structs.update(s["name"] for s in item.get("structs", []))'
)

with open('multi_repo.py', 'w', encoding='utf-8') as f:
    f.write(content)
