import os
import json
import re
from tree_sitter import Language, Parser
import tree_sitter_cpp

# ==================================================
# CONFIG
# ==================================================

REPO_ROOT = r"C:\Users\Dell\OneDrive\Desktop\step1\ACIS\ACIS"
MAX_FILES = None     # Set to None to parse the entire repository, or an integer (e.g. 5) to limit

VALID_EXTENSIONS = {
    ".h",
    ".hpp",
    ".hxx",
    ".hh",
    ".err",
    ".cpp",
    ".cc",
    ".cxx",
    ".c"
}

# ==================================================
# TREE-SITTER SETUP
# ==================================================

CPP_LANGUAGE = Language(tree_sitter_cpp.language())
parser = Parser(CPP_LANGUAGE)

# ==================================================
# GLOBAL CLASSIFICATION DICTIONARIES
# ==================================================

STL_CLASSES = {
    "unique_ptr", "shared_ptr", "weak_ptr", "vector", "string", "list", "map", "set",
    "unordered_map", "unordered_set", "ostream", "istream", "iostream", "exception",
    "runtime_error", "invalid_argument", "allocator", "pair"
}

EXTERNAL_BASE_CLASSES = {
    "acis_ha_part_entity_mgr", "acis_ha_part_entity_mgr_factory", "acis_ha_part_entity_mgr_notifying",
    "CATBaseUnknown", "CATTopObject", "CATGeomHashTableBase", "CATCGMHashTableBase",
    "CATCGMVirtual", "CATCGMJournal", "CATTopology", "CATSurface", "CATCurve", "CATGeometry",
    "CATICGMUnknown", "CATMathStream", "CATMathStreamImpl", "ExportedByJS0DSPA", "ExportedByJS0CTYP",
    "ExportedByJS0ERROR", "ExportedByCATGMGeometricInterfaces", "ExportedByJS0INF",
    "ExportedByCATGMModelInterfaces", "ExportedByCATMathematics", "ExportedByYP00IMPL",
    "ExportedByCGMComponent", "ExportedByJS0CORBA", "IDispatch", "IUnknown", "CObject",
    "streambuf", "ios", "Operator", "__releaser__CGM", "CGMReleasable_uptr",
    "direct_render_mesh_manager", "rubberband_circle", "hoops_acis_entity_converter",
    "acis_hps_part_entity_mgr", "acis_hps_part_entity_mgr_factory", "hps_acis_entity_converter",
    "EventHandler", "WarningHandler", "ErrorHandler", "rubberband_driver", "rubberband_manager",
    "scheme_entity_converter"
}

BLACKLISTED_NAMES = {
    "ENTER_FUNCTION", "PARENT", "THIS", "SYS_RET_CLASS_TYPE", 
    "SYS_OM_META_CLASS_CHECK", "SURFACE_PROP", "THIS_FUNCTION", 
    "DECLARE_MESSAGE", "DECLARE_MESSAGE_WITH_LOB", "DECLARE_MESSAGE_WITH_ATTR",
    "MASTER_ATTRIB_DECL", "MASTER_ENTITY_DECL"
}

# ==================================================
# PARSE SINGLE FILE
# ==================================================

def parse_file(file_path):
    with open(file_path, "rb") as f:
        code = f.read()

    tree = parser.parse(code)

    classes = {}
    structs = {}
    enums = {}
    typedefs = {}
    namespaces = {}
    includes = set()
    inheritance = []
    temp_functions = []

    def text(node):
        return code[node.start_byte:node.end_byte].decode("utf-8", errors="ignore")

    comments = []
    def walk_comments(n):
        if n.type == 'comment':
            comments.append({
                "text": text(n),
                "end_line": n.end_point[0] + 1
            })
        for c in n.children:
            walk_comments(c)
    walk_comments(tree.root_node)

    def clean_comment(comment_text):
        lower_c = comment_text.lower()
        if "copyright" in lower_c or "license" in lower_c:
            return None
        if "generated by" in lower_c or "generated file" in lower_c:
            return None
        if "revision" in lower_c or "history" in lower_c:
            return None
        
        stripped = comment_text.replace('/', '').replace('*', '').strip()
        if not stripped:
            return None
        if len(stripped) > 5 and len(set(stripped)) == 1 and stripped[0] in '=-_':
            return None
            
        lines = comment_text.split('\n')
        cleaned_lines = []
        for line in lines:
            line = line.strip()
            if line.startswith('///'): line = line[3:]
            elif line.startswith('//'): line = line[2:]
            elif line.startswith('/**'): line = line[3:]
            elif line.startswith('/*'): line = line[2:]
            
            if line.endswith('*/'): line = line[:-2]
            if line.startswith('*'): line = line[1:]
            
            line = line.strip()
            if line:
                cleaned_lines.append(line)
                
        if not cleaned_lines:
            return None
            
        import re
        raw_text = "\n".join(cleaned_lines)
        raw_text = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', raw_text)
        raw_text = re.sub(r'<[^>]+>', '\n', raw_text)
        raw_text = raw_text.replace('&nbsp;', ' ').replace('&lt;', '<').replace('&gt;', '>').replace('&amp;', '&')
        
        raw_lines = raw_text.split('\n')
        normalized_lines = []
        for line in raw_lines:
            line = re.sub(r'[ \t]+', ' ', line).strip()
            if line:
                normalized_lines.append(line)
                
        final_lines = []
        for line in normalized_lines:
            if re.match(r'^(@[a-zA-Z]+|Role:|Effect:|Journal:|Product\(s\):|Limitations:|Technical Articles:|Note:)', line, re.IGNORECASE):
                final_lines.append("\n" + line)
            else:
                final_lines.append(" " + line)
                
        text_out = "".join(final_lines).strip()
        text_out = re.sub(r'[ \t]+', ' ', text_out)
        text_out = re.sub(r'\n\s+', '\n', text_out).strip()
        
        return text_out

    valid_comments = []
    for c in comments:
        cleaned = clean_comment(c["text"])
        if cleaned:
            valid_comments.append({
                "text": cleaned,
                "end_line": c["end_line"]
            })
            
    valid_comments.sort(key=lambda x: x["end_line"])

    all_declaration_lines = set()
    def record_declarations(n):
        if n.type in ("declaration", "field_declaration", "function_definition", "class_specifier", "struct_specifier", "enum_specifier", "type_definition"):
            all_declaration_lines.add(n.start_point[0] + 1)
        for child in n.children:
            record_declarations(child)
    record_declarations(tree.root_node)

    def get_closest_comment(entity_line):
        closest = None
        min_dist = float('inf')
        for c in valid_comments:
            dist = entity_line - c["end_line"]
            if 0 <= dist <= 3:
                intervening = [l for l in all_declaration_lines if c["end_line"] < l < entity_line]
                if not intervening:
                    if dist < min_dist:
                        min_dist = dist
                        closest = c["text"]
        return closest if closest is not None else ""

    # Helpers for function AST analysis
    def get_declarator_info(decl_node):
        curr = decl_node
        is_pointer = False
        is_reference = False
        is_func_ptr_var = False
        while curr:
            if curr.type == "pointer_declarator":
                is_pointer = True
                is_func_ptr_var = True
                curr = curr.child_by_field_name("declarator")
            elif curr.type == "reference_declarator":
                is_reference = True
                is_func_ptr_var = True
                curr = curr.child_by_field_name("declarator")
            elif curr.type == "parenthesized_declarator":
                if len(curr.children) >= 3:
                    curr = curr.children[1]
                else:
                    curr = None
            else:
                break
        return curr, is_pointer, is_reference, is_func_ptr_var

    def get_return_type_modifiers(func_decl_node):
        curr = func_decl_node.parent
        modifiers = []
        while curr:
            if curr.type == "pointer_declarator":
                modifiers.append("*")
            elif curr.type == "reference_declarator":
                modifiers.append("&")
            elif curr.type in ("declaration", "field_declaration", "function_definition"):
                break
            curr = curr.parent
        return "".join(reversed(modifiers))

    def find_owning_class_or_struct(node):
        curr = node.parent
        while curr:
            if curr.type in ("class_specifier", "struct_specifier"):
                name_node = curr.child_by_field_name("name")
                if name_node:
                    return text(name_node).strip()
                # sibling name fallback
                p = curr.parent
                if p:
                    try:
                        idx = p.children.index(curr)
                        for sib in p.children[idx+1:]:
                            if sib.type in ("identifier", "type_identifier"):
                                return text(sib).strip()
                            if sib.type in ("{", "class_body", "compound_statement", ";"):
                                break
                    except:
                        pass
            curr = curr.parent
        return None

    def get_access_specifier(node):
        curr = node
        while curr and curr.parent and curr.parent.type != "class_body":
            curr = curr.parent
        if curr and curr.parent and curr.parent.type == "class_body":
            siblings = curr.parent.children
            try:
                idx = siblings.index(curr)
                for i in range(idx - 1, -1, -1):
                    sib = siblings[i]
                    if sib.type == "access_specifier" or (sib.type == "labeled_statement" and text(sib).strip().endswith(":")):
                        txt = text(sib).strip().rstrip(":")
                        if txt in ("public", "protected", "private"):
                            return txt
            except:
                pass
        # default access
        ancestor = node.parent
        while ancestor:
            if ancestor.type == "class_specifier":
                return "private"
            if ancestor.type == "struct_specifier":
                return "public"
            ancestor = ancestor.parent
        return None

    def check_modifiers(node):
        curr = node
        while curr and curr.type not in ("declaration", "field_declaration", "function_definition"):
            curr = curr.parent
        is_virtual = False
        is_static = False
        is_inline = False
        if curr:
            for child in curr.children:
                txt = text(child).strip()
                if txt == "virtual":
                    is_virtual = True
                elif txt == "static":
                    is_static = True
                elif txt == "inline":
                    is_inline = True
            if "inline" in text(curr):
                is_inline = True
        return is_virtual, is_static, is_inline

    def get_return_type(node):
        curr = node
        while curr and curr.type not in ("declaration", "field_declaration", "function_definition"):
            curr = curr.parent
        if curr:
            type_node = curr.child_by_field_name("type")
            if type_node:
                type_text = text(type_node).strip()
                # Recover macro-corrupted return types (e.g. DECL_BASE outcome func(...))
                if type_text.startswith("DECL_") or type_text == "_EXPORT_MACRO":
                    children = curr.children
                    try:
                        t_idx = children.index(type_node)
                        n_idx = children.index(node)
                        for i in range(t_idx + 1, n_idx):
                            child = children[i]
                            if child.type == "ERROR":
                                for sub in child.children:
                                    if sub.type in ("identifier", "type_identifier", "primitive_type"):
                                        return text(sub).strip()
                            elif child.type in ("identifier", "type_identifier", "primitive_type"):
                                return text(child).strip()
                    except:
                        pass
                return type_text
        return "void"

    def get_parameters(node):
        params_node = node.child_by_field_name("parameters")
        if not params_node:
            for child in node.children:
                if child.type == "parameter_list":
                    params_node = child
                    break
        params_list = []
        if params_node:
            for child in params_node.children:
                if child.type in ("parameter_declaration", "optional_parameter_declaration", "variadic_parameter_declaration"):
                    decl_node = child.child_by_field_name("declarator")
                    
                    def get_id(n):
                        if n.type in ("identifier", "type_identifier", "field_identifier"):
                            return text(n)
                        for c in n.children:
                            res = get_id(c)
                            if res: return res
                        return None
                        
                    name = get_id(decl_node) if decl_node else ""
                    full_text = text(child).strip()
                    if "=" in full_text:
                        full_text = full_text.split("=", 1)[0].strip()
                        
                    if name and name in full_text:
                        idx = full_text.rfind(name)
                        type_str = full_text[:idx].strip()
                        post = full_text[idx+len(name):].strip()
                        type_str = (type_str + " " + post).strip()
                        params_list.append({"type": type_str, "name": name})
                    else:
                        params_list.append({"type": full_text, "name": name})
        return params_list

    def check_const_qualifier(node):
        has_seen_param_list = False
        for child in node.children:
            if child.type == "parameter_list":
                has_seen_param_list = True
            if has_seen_param_list:
                if text(child).strip() == "const":
                    return True
        return False

    def get_namespace_ownership(node):
        curr = node.parent
        ns_list = []
        while curr:
            if curr.type == "namespace_definition":
                for child in curr.children:
                    if child.type in ("identifier", "namespace_identifier"):
                        ns_list.append(text(child).strip())
                        break
            curr = curr.parent
        if ns_list:
            return "::".join(reversed(ns_list))
        return None

    def is_legitimate_name(name, class_owner, local_types):
        if not name:
            return False
            
        if name.startswith("operator") or "operator" in name:
            return True
        
        # If the name contains parentheses, spaces, or newlines, it's a macro or corrupted declaration
        if "(" in name or ")" in name or " " in name or "\t" in name or "\n" in name or "\r" in name:
            return False
            
        clean = name.lstrip("~").split("::")[-1].strip()
        
        # Check against blacklist
        if clean in BLACKLISTED_NAMES:
            # Allow constructor/destructor of a class named like a blacklisted macro
            if class_owner and clean == class_owner.lstrip("~").split("::")[-1].strip():
                pass
            elif clean in local_types:
                pass
            else:
                return False
        
        # Exclude ALL_CAPS macro pseudo-functions
        if name.isupper() and len(name) > 1:
            if class_owner and clean == class_owner.lstrip("~").split("::")[-1].strip():
                return True
            if clean in local_types:
                return True
            return False
        return True

    def walk(node):
        # ==========================================
        # INCLUDES
        # ==========================================
        if node.type == "preproc_include":
            include_text = text(node)
            if '"' in include_text:
                try:
                    includes.add(include_text.split('"')[1])
                except:
                    pass

        # ==========================================
        # NAMESPACES
        # ==========================================
        if node.type == "namespace_definition":
            for child in node.children:
                if child.type in ("identifier", "namespace_identifier"):
                    ns_name = text(child)
                    if ns_name not in namespaces:
                        namespaces[ns_name] = {"name": ns_name, "line_number": node.start_point[0] + 1}

        # ==========================================
        # CLASSES & INHERITANCE
        # ==========================================
        if node.type == "class_specifier":
            def get_class_info(n):
                outer = n
                p = n.parent
                if p and p.type in ("declaration", "function_definition"):
                    if p.child_by_field_name('type') == n:
                        outer = p
                
                if outer.type == "function_definition":
                    return True, code[outer.start_byte:outer.end_byte]
                elif outer.type == "declaration":
                    has_body = False
                    for child in outer.children:
                        if child.type in ("class_body", "compound_statement"):
                            has_body = True
                            break
                    if has_body:
                        return True, code[outer.start_byte:outer.end_byte]
                    return False, None
                
                # Sibling fallback for ERROR parents (e.g. macro-corrupted class blocks)
                if p:
                    try:
                        children = p.children
                        idx = children.index(n)
                        is_def = False
                        body_start = None
                        for sib in children[idx+1:]:
                            if sib.type in ("{", "class_body", "compound_statement"):
                                is_def = True
                                body_start = sib.start_byte
                                break
                            if sib.type == ";":
                                break
                        if is_def and body_start is not None:
                            return True, code[n.start_byte:body_start]
                    except:
                        pass
                
                if n.child_by_field_name('body') is not None:
                    return True, code[n.start_byte:n.end_byte]
                return False, None

            is_def, bytes_data = get_class_info(node)
            if is_def and bytes_data:
                cut_idx = len(bytes_data)
                for i, b in enumerate(bytes_data):
                    if b in (ord('{'), ord(';')):
                        cut_idx = i
                        break

                header_text = bytes_data[:cut_idx].decode("utf-8", errors="ignore").strip()
                header_text = re.sub(r'//.*', '', header_text)
                header_text = re.sub(r'/\*.*?\*/', '', header_text, flags=re.DOTALL)
                header_text = header_text.strip()

                tokens = re.findall(r'[a-zA-Z_]\w*|:', header_text)
                if tokens and tokens[0] == "class":
                    colon_idx = len(tokens)
                    if ":" in tokens:
                        colon_idx = tokens.index(":")

                    decl_tokens = tokens[1:colon_idx]
                    class_name = None

                    if len(decl_tokens) == 1:
                        class_name = decl_tokens[0]
                    elif len(decl_tokens) >= 2:
                        first_token = decl_tokens[0]
                        if first_token.startswith("DECL_") or first_token == "_EXPORT_MACRO":
                            class_name = decl_tokens[1]
                        else:
                            class_name = decl_tokens[0]

                    if class_name:
                        doc = get_closest_comment(node.start_point[0] + 1)
                        if class_name not in classes or not classes[class_name].get("documentation"):
                            classes[class_name] = {"name": class_name, "documentation": doc, "line_number": node.start_point[0] + 1}

                        # Extract base classes safely
                        base_classes = []
                        colon_pos = header_text.find(':')
                        if colon_pos != -1:
                            base_clause = header_text[colon_pos + 1:].strip()
                            parts = base_clause.split(',')
                            for part in parts:
                                part = part.strip()
                                if not part or '(' in part:
                                    continue
                                
                                part_tokens = part.split()
                                access_specifiers = {"public", "protected", "private", "virtual"}
                                filtered_tokens = [t for t in part_tokens if t not in access_specifiers]
                                
                                if filtered_tokens:
                                    base_type = filtered_tokens[0]
                                    is_template = '<' in base_type
                                    base_type = base_type.split('<')[0].strip()
                                    base_type = base_type.split('::')[-1].strip()
                                    
                                    if re.match(r'^[a-zA-Z_]\w*$', base_type):
                                        base_classes.append((base_type, is_template))

                        for base_class, is_template in base_classes:
                            inheritance.append({
                                "class": class_name,
                                "base": base_class,
                                "is_template": is_template
                            })

        # ==========================================
        # MACRO-GENERATED CLASSES (MASTER_ATTRIB_DECL & MASTER_ENTITY_DECL)
        # ==========================================
        if node.type == "call_expression":
            fn_node = node.child_by_field_name('function')
            if fn_node:
                fn_name = text(fn_node).strip()
                if fn_name in ("MASTER_ATTRIB_DECL", "MASTER_ENTITY_DECL"):
                    args_node = node.child_by_field_name('arguments')
                    if args_node:
                        args = [child for child in args_node.children if child.type not in ("(", ")", ",")]
                        if args:
                            class_name = text(args[0]).strip()
                            if class_name:
                                doc = get_closest_comment(node.start_point[0] + 1)
                                if class_name not in classes or not classes[class_name].get("documentation"):
                                    classes[class_name] = {"name": class_name, "documentation": doc, "line_number": node.start_point[0] + 1}
                                base_class = "ATTRIB" if fn_name == "MASTER_ATTRIB_DECL" else "ENTITY"
                                inheritance.append({
                                    "class": class_name,
                                    "base": base_class,
                                    "is_template": False
                                })

        # ==========================================
        # STRUCTS
        # ==========================================
        if node.type == "struct_specifier":
            type_ids = []
            for child in node.children:
                if child.type == "type_identifier":
                    type_ids.append(text(child))
            if type_ids:
                s_name = type_ids[-1]
                doc = get_closest_comment(node.start_point[0] + 1)
                if s_name not in structs or not structs[s_name].get("documentation"):
                    structs[s_name] = {"name": s_name, "documentation": doc, "line_number": node.start_point[0] + 1}

        # ==========================================
        # ENUMS
        # ==========================================
        if node.type == "enum_specifier":
            e_name = None
            e_values = []
            for child in node.children:
                if child.type == "type_identifier":
                    e_name = text(child)
                elif child.type == "enumerator_list":
                    for sub in child.children:
                        if sub.type == "enumerator":
                            name_node = sub.child_by_field_name("name")
                            if name_node:
                                e_values.append(text(name_node))
            if e_name:
                doc = get_closest_comment(node.start_point[0] + 1)
                if e_name not in enums or not enums[e_name].get("documentation"):
                    enums[e_name] = {"name": e_name, "documentation": doc, "line_number": node.start_point[0] + 1, "values": e_values}

        # ==========================================
        # TYPEDEFS
        # ==========================================
        if node.type == "type_definition":
            decl = node.child_by_field_name('declarator')
            if decl:
                def find_alias_identifier(n):
                    if n.type in ("type_identifier", "identifier"):
                        return n
                    for child in n.children:
                        res = find_alias_identifier(child)
                        if res:
                            return res
                    return None
                
                alias_node = find_alias_identifier(decl)
                if alias_node:
                    alias_name = text(alias_node).strip()
                    if alias_name:
                        doc = get_closest_comment(node.start_point[0] + 1)
                        if alias_name not in typedefs or not typedefs[alias_name].get("documentation"):
                            typedefs[alias_name] = {"name": alias_name, "documentation": doc, "line_number": node.start_point[0] + 1}

        # ==========================================
        # FUNCTION DECLARATIONS & DEFINITIONS
        # ==========================================
        if node.type == "function_declarator":
            # Check if this function_declarator is inside a typedef or parameter declaration
            curr = node.parent
            skip = False
            while curr:
                if curr.type in ("type_definition", "parameter_declaration"):
                    skip = True
                    break
                if curr.type in ("compound_statement", "class_body", "struct_specifier", "class_specifier"):
                    break
                curr = curr.parent

            if not skip:
                decl = node.child_by_field_name('declarator')
                if decl:
                    name_node, is_ptr, is_ref, is_func_ptr_var = get_declarator_info(decl)
                    
                    # If it's a function pointer variable, or name node is itself a function declarator (macro), skip it
                    if name_node and name_node.type != "function_declarator" and not is_func_ptr_var:
                        class_owner = None
                        fn_name = ""
                        
                        # Resolve qualifiers and namespaces
                        if name_node.type == "qualified_identifier":
                            scope_node = name_node.child_by_field_name("scope")
                            name_child = name_node.child_by_field_name("name")
                            if scope_node:
                                class_owner = text(scope_node).strip()
                            if name_child:
                                fn_name = text(name_child).strip()
                        elif name_node.type == "template_function":
                            name_child = name_node.child_by_field_name('name')
                            if name_child:
                                inner_name, _, _, _ = get_declarator_info(name_child)
                                if inner_name and inner_name.type != "function_declarator":
                                    fn_name = text(inner_name).strip()
                        else:
                            fn_name = text(name_node).strip()

                        if fn_name:
                            if not class_owner:
                                class_owner = find_owning_class_or_struct(node)
                            
                            is_method = class_owner is not None
                            is_virtual, is_static, is_inline = check_modifiers(node)
                            is_const = check_const_qualifier(node)
                            ns_owner = get_namespace_ownership(node)
                            access = get_access_specifier(node) if is_method else None
                            params = get_parameters(node)
                            
                            # Get base return type
                            ret_type = get_return_type(node)
                            
                            # Append pointer/reference modifiers from parent chain
                            mods = get_return_type_modifiers(node)
                            if mods and ret_type:
                                ret_type = f"{ret_type} {mods}".strip()
                            elif mods:
                                ret_type = mods

                            # Clean constructor/destructor return types
                            clean_name = fn_name.lstrip("~")
                            if is_method and class_owner and clean_name == class_owner.split("::")[-1].strip():
                                ret_type = ""

                            # Check if pure virtual method
                            is_pure = False
                            p = node.parent
                            while p and p.type not in ("declaration", "field_declaration", "function_definition"):
                                p = p.parent
                            if p:
                                for child in p.children:
                                    if child.type == "pure_specifier":
                                        is_pure = True
                                        break

                            temp_functions.append({
                                "name": fn_name,
                                "return_type": ret_type,
                                "parameters": params,
                                "is_method": is_method,
                                "class_owner": class_owner,
                                "namespace_owner": ns_owner,
                                "access": access,
                                "is_virtual": is_virtual,
                                "is_static": is_static,
                                "is_inline": is_inline,
                                "is_const": is_const,
                                "is_pure_virtual": is_pure,
                                "line_number": node.start_point[0] + 1,
                                "documentation": get_closest_comment(node.start_point[0] + 1)
                            })

        for child in node.children:
            walk(child)

    walk(tree.root_node)

    # Filter and categorize functions and methods (Priority 1 & 2)
    local_types = set(classes.keys()).union(structs.keys()).union(enums.keys()).union(typedefs)
    final_functions = []
    final_methods = []
    rel_path = os.path.relpath(file_path, REPO_ROOT).replace("\\", "/")

    for fn in temp_functions:
        name = fn["name"]
        class_owner = fn["class_owner"]
        
        if not is_legitimate_name(name, class_owner, local_types):
            continue

        fn["source_file"] = rel_path

        if fn["is_method"]:
            final_methods.append(fn)
        else:
            final_functions.append(fn)

    return {
        "file": os.path.basename(file_path),
        "path": rel_path,
        "classes": sorted(list(classes.values()), key=lambda x: x["name"]),
        "structs": sorted(list(structs.values()), key=lambda x: x["name"]),
        "enums": sorted(list(enums.values()), key=lambda x: x["name"]),
        "typedefs": sorted(list(typedefs.values()), key=lambda x: x["name"]),
        "namespaces": sorted(list(namespaces.values()), key=lambda x: x["name"]),
        "includes": sorted(includes),
        "functions": final_functions,
        "methods": final_methods,
        "inheritance": inheritance
    }

# ==================================================
# REPOSITORY WALKER
# ==================================================

# 1. Pre-scan to find total matching files for progress percentage
print("Pre-scanning repository to count files...")
files_to_parse = []
include_dir = os.path.join(REPO_ROOT, "include")
for root, dirs, files in os.walk(include_dir):
    for file in files:
        ext = os.path.splitext(file)[1].lower()
        if ext in VALID_EXTENSIONS:
            files_to_parse.append(os.path.join(root, file))

total_matching_files = len(files_to_parse)
print(f"Found {total_matching_files} files to parse.")

# 2. Setup output files
temp_jsonl_file = "all_entities.jsonl"
failed_files_log = "failed_files.json"
summary_file = "parse_summary.json"

# Remove any pre-existing temp file
if os.path.exists(temp_jsonl_file):
    os.remove(temp_jsonl_file)

global_stats = {
    "total_files_parsed": 0,
    "total_functions": 0,
    "total_methods": 0,
    "total_classes": 0,
    "total_includes": 0,
    "total_structs": 0,
    "total_enums": 0,
    "total_typedefs": 0,
    "total_namespaces": 0,
    "total_inheritance_edges": 0,
    "failed_files_count": 0
}

failed_files = []
count = 0
progress_interval = 50  # Report progress every 50 files

print("\nStarting parsing process...")

# Open the JSONL file for incremental writing
with open(temp_jsonl_file, "a", encoding="utf-8") as jsonl_f:
    for file_path in files_to_parse:
        file_name = os.path.basename(file_path)
        try:
            parsed = parse_file(file_path)
            
            # Write to JSONL immediately
            jsonl_f.write(json.dumps(parsed, ensure_ascii=False) + "\n")
            
            # Accumulate temporary statistics
            count += 1
            
            # Progress reporting
            if count % progress_interval == 0 or count == total_matching_files:
                pct = (count / total_matching_files) * 100
                print(f"[Progress] Parsed {count}/{total_matching_files} files ({pct:.1f}%)")

        except Exception as e:
            error_msg = str(e)
            print(f"[ERROR] Failed to parse: {file_name}. Reason: {error_msg}")
            
            failed_files.append({
                "file": file_name,
                "path": os.path.relpath(file_path, REPO_ROOT).replace("\\", "/"),
                "error": error_msg
            })

        # Apply MAX_FILES limit if defined
        if MAX_FILES and count >= MAX_FILES:
            print(f"Reached MAX_FILES limit of {MAX_FILES}. Stopping.")
            break

# ==================================================
# SAVE OUTPUT, ENRICH INHERITANCE & MERGE
# ==================================================

output_file = "code_base.json"

# Write failed files report
with open(failed_files_log, "w", encoding="utf-8") as f_fail:
    json.dump(failed_files, f_fail, indent=2)

def indent_string(s, spaces=2):
    indentation = " " * spaces
    return indentation + s.replace("\n", "\n" + indentation)

def resolve_qualified_scope(class_owner_raw, ns_owner_raw, global_classes_and_structs, global_namespaces):
    if not class_owner_raw:
        return None, ns_owner_raw, False

    parts = [p.strip() for p in class_owner_raw.split("::") if p.strip()]
    if not parts:
        return None, ns_owner_raw, False

    # Find if any part is a known class/struct
    class_idx = -1
    for i, part in enumerate(parts):
        if part in global_classes_and_structs:
            class_idx = i
            break

    # Fallback: check if the last part is not a namespace
    if class_idx == -1:
        if parts[-1] in global_namespaces:
            class_idx = -1
        else:
            # Assume last part is class if it's not in namespaces
            class_idx = len(parts) - 1

    if class_idx != -1:
        class_parts = parts[class_idx:]
        ns_parts = parts[:class_idx]
        
        resolved_class = "::".join(class_parts)
        
        # Merge namespaces
        all_ns = []
        if ns_owner_raw:
            all_ns.extend([p.strip() for p in ns_owner_raw.split("::") if p.strip()])
        all_ns.extend(ns_parts)
        resolved_ns = "::".join(all_ns) if all_ns else None
        
        return resolved_class, resolved_ns, True
    else:
        # All parts are namespaces
        all_ns = []
        if ns_owner_raw:
            all_ns.extend([p.strip() for p in ns_owner_raw.split("::") if p.strip()])
        all_ns.extend(parts)
        resolved_ns = "::".join(all_ns) if all_ns else None
        
        return None, resolved_ns, False

# If we parsed anything, compile and enrich the final all_entities.json
if os.path.exists(temp_jsonl_file):
    print("\nPhase 1: Compiling global class and namespace indexes for refinement...")
    global_classes = set()
    global_structs = set()
    global_namespaces = set()
    
    with open(temp_jsonl_file, "r", encoding="utf-8") as jsonl_f:
        for line in jsonl_f:
            if line.strip():
                item = json.loads(line)
                global_classes.update(c["name"] for c in item.get("classes", []))
                global_structs.update(s["name"] for s in item.get("structs", []))
                global_namespaces.update(ns["name"] for ns in item.get("namespaces", []))
                
    global_classes_and_structs = global_classes.union(global_structs)

    # Re-initialize global statistics for exact post-processed reporting
    global_stats = {
        "total_files_parsed": 0,
        "total_functions": 0,
        "total_methods": 0,
        "total_classes": 0,
        "total_includes": 0,
        "total_structs": 0,
        "total_enums": 0,
        "total_typedefs": 0,
        "total_namespaces": 0,
        "total_inheritance_edges": 0,
        "failed_files_count": len(failed_files)
    }

    print("Phase 2: Compiling final enriched and resolved all_entities.json...")
    with open(output_file, "w", encoding="utf-8") as f_out:
        f_out.write("[\n")
        first = True
        with open(temp_jsonl_file, "r", encoding="utf-8") as jsonl_f:
            for line in jsonl_f:
                if line.strip():
                    if not first:
                        f_out.write(",\n")
                    
                    parsed_line = json.loads(line)
                    
                    # Clean up inheritance edges globally (Priority 4)
                    final_inheritance = []
                    for inh in parsed_line.get("inheritance", []):
                        final_inheritance.append({
                            "class": inh.get("class"),
                            "base": inh.get("base")
                        })

                    # Resolve function vs method classification globally
                    resolved_functions = []
                    resolved_methods = []

                    def normalize_name(name):
                        if name and name.startswith("operator"):
                            s = name[8:].strip()
                            if not s: return name
                            if s.startswith("new") or s.startswith("delete"):
                                return "operator " + s.replace(" ", "").replace("\t", "")
                            if not s[0].isalpha():
                                return "operator" + s.replace(" ", "").replace("\t", "")
                            return "operator " + re.sub(r'\s+', ' ', s)
                        return name

                    def process_fn(fn):
                        class_owner = fn.get("class_owner")
                        is_meth = fn.get("is_method", False)
                        
                        if is_meth and not class_owner:
                            is_meth = False
                            
                        doc = fn.get("documentation")
                        if doc is None: doc = ""
                        
                        name = normalize_name(fn.get("name"))
                        
                        if is_meth:
                            resolved_methods.append({
                                "class": class_owner,
                                "name": name,
                                "return_type": fn.get("return_type", ""),
                                "parameters": fn.get("parameters", []),
                                "line_number": fn.get("line_number", 0),
                                "documentation": doc
                            })
                        else:
                            resolved_functions.append({
                                "name": name,
                                "return_type": fn.get("return_type", ""),
                                "parameters": fn.get("parameters", []),
                                "line_number": fn.get("line_number", 0),
                                "documentation": doc
                            })

                    for fn in parsed_line.get("functions", []):
                        process_fn(fn)

                    for m in parsed_line.get("methods", []):
                        process_fn(m)

                    # Enforce strictly the final canonical schema
                    parsed_line = {
                        "file": parsed_line.get("file", ""),
                        "path": parsed_line.get("path", ""),
                        "includes": parsed_line.get("includes", []),
                        "classes": parsed_line.get("classes", []),
                        "structs": parsed_line.get("structs", []),
                        "enums": parsed_line.get("enums", []),
                        "typedefs": parsed_line.get("typedefs", []),
                        "namespaces": parsed_line.get("namespaces", []),
                        "functions": resolved_functions,
                        "methods": resolved_methods,
                        "inheritance": final_inheritance
                    }

                    # Update global stats
                    global_stats["total_files_parsed"] += 1
                    global_stats["total_functions"] += len(resolved_functions)
                    global_stats["total_methods"] += len(resolved_methods)
                    global_stats["total_classes"] += len(parsed_line.get("classes", []))
                    global_stats["total_structs"] += len(parsed_line.get("structs", []))
                    global_stats["total_namespaces"] += len(parsed_line.get("namespaces", []))
                    global_stats["total_includes"] += len(parsed_line.get("includes", []))
                    global_stats["total_enums"] += len(parsed_line.get("enums", []))
                    global_stats["total_typedefs"] += len(parsed_line.get("typedefs", []))
                    global_stats["total_inheritance_edges"] += len(parsed_line.get("inheritance", []))

                    formatted_item = indent_string(json.dumps(parsed_line, indent=2, ensure_ascii=False))
                    f_out.write(formatted_item)
                    first = False
        f_out.write("\n]\n")
        
    # Clean up temp file
    try:
        os.remove(temp_jsonl_file)
    except:
        pass

# Write summary file
with open(summary_file, "w", encoding="utf-8") as f_sum:
    json.dump(global_stats, f_sum, indent=2)

print("\n==================================================")
print("PARSING COMPLETE")
print("==================================================")
print(f"Total Files Searched : {total_matching_files}")
print(f"Successfully Parsed  : {global_stats['total_files_parsed']}")
print(f"Failed Files Count   : {global_stats['failed_files_count']} (Details in '{failed_files_log}')")
print("--------------------------------------------------")
print(f"Total Functions      : {global_stats['total_functions']}")
print(f"Total Methods        : {global_stats['total_methods']}")
print(f"Total Classes        : {global_stats['total_classes']}")
print(f"Total Structs        : {global_stats['total_structs']}")
print(f"Total Enums          : {global_stats['total_enums']}")
print(f"Total Typedefs       : {global_stats['total_typedefs']}")
print(f"Total Namespaces     : {global_stats['total_namespaces']}")
print(f"Total Inheritance Edges : {global_stats['total_inheritance_edges']}")
print(f"Total Includes       : {global_stats['total_includes']}")
print("--------------------------------------------------")
print(f"Final JSON Output    : {output_file}")
print(f"Summary JSON Output  : {summary_file}")
print("==================================================")